version: '3'
services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile  # Wskazuje na Twoją lokalną ścieżkę do Dockerfile
    ports:
      - "8080:80"
    volumes:
      - /c/xampp/htdocs/programs/Tarkonprograms:/var/www/html

